#spring.datasource:
#  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#  #shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
#  username: postgres
#  password: Ivan230691
#spring.h2.console.enabled: true # http://localhost:8080/h2-console/
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  default-serialization-format: application/json
server.port: 8080
spring.devtools:
  restart:
    enabled: false # Do not enable this with ObjectValues as variables!
camunda.bpm.job-execution:
  #   deployment-aware: true
  wait-time-in-millis: 5000
  max-wait: 10000


spring.cloud.stream.bindings.output.destination: test
spring.cloud.stream.bindings.output.content-type: application/json

spring.cloud.stream.bindings.output2.destination: test2
spring.cloud.stream.bindings.output2.content-type: application/json

spring.cloud.stream.bindings.input.destination: ComundaTopic
spring.cloud.stream.bindings.input.content-type: application/json


spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
spring.cloud.stream.kafka.binder.brokers: localhost:9092

#camunda.bpm.database.type: postgres
#spring.datasource.url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/camunda?useSSL=false
#spring.datasource.username: postgres
#spring.datasource.password: Ivan230691
#
#spring.datasource.driver-class-name: org.postgresql.Driver
#camunda.bpm.database.schema-update: true
#camunda.bpm.database.table-prefix: camunda.

spring:

  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/camunda
    username: postgres
    password: Ivan230691

    hikari:
      jdbc-url: jdbc:postgresql://${DATASOURCE_HOST:localhost}:5432/camunda
      username: postgres
      password: Ivan230691
      driver-class-name: org.postgresql.Driver
      pool-name: CAMUNDA-HIKARI-POOL
      idle-timeout: 3000
      minimum-idle: 30
      maximum-pool-size: 10
      connection-timeout: 2000
      connection-test-query: select 1
      transaction-isolation: TRANSACTION_READ_COMMITTED
